[package]
name = "simconnect"
license = "MIT"
description = "Rust bindings for SimConnect"
version = "0.2.0"
authors = ["Connor T"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.65"
